# -*- coding: utf-8 -*-
"""Bảng dịch VI -> EN cho toàn bộ popup hướng dẫn (9 chế độ x 3 trang).

Khoá = chuỗi tiếng Việt ĐÚNG NGUYÊN VĂN như trong mockup (sau bước clean_text,
tức là đã bỏ các glyph font không có như ① → ...). Giá trị = bản dịch tiếng Anh.

Quy ước dịch:
  - Tiêu đề/chip/tab/nhãn IN HOA giữ nguyên kiểu in hoa.
  - Câu mô tả viết hoa chữ đầu như tiếng Việt tương ứng.
  - Thuật ngữ dùng thống nhất với game: Anchor, Hint, Undo, Star, Floor,
    Invisible Wall, Draft Wall, Finish hole (F), Start stair (S).
  - Chuỗi chỉ gồm ký hiệu/số (S, F, =, <, >, 03, 00:45, ...) không cần dịch —
    builder sẽ tự dùng lại bản VI khi thiếu khoá.
"""

EN: dict[str, str] = {
    # ------------------------------------------------------------------ blindmemory
    "BLIND MEMORY MAZE": "BLIND MEMORY MAZE",
    "Pha Đếm Ngược Ghi Nhớ": "The Memorize Countdown",
    "QUY TẮC PHA GHI NHỚ": "MEMORY PHASE RULES",
    "TIẾP THEO: TƯỜNG BIẾN MẤT (2/3) ›": "NEXT: WALLS VANISH (2/3) ›",
    "Bỏ qua hướng dẫn & Vào ghi nhớ ngay": "Skip guide & start memorizing now",
    "ĐẾM NGƯỢC 3 GIÂY": "3-SECOND COUNTDOWN",
    "TƯỜNG BIẾN MẤT": "WALLS VANISH",
    "DỰNG TƯỜNG NHÁP": "PLACE DRAFT WALLS",
    "Tường Hiển Thị Toàn Bộ Khi Bắt Đầu:": "The Full Maze Shows At The Start:",
    "Bạn có 3 giây đếm ngược (3.. 2.. 1.. GO!) để nhìn thấy toàn bộ mê cung thật.": "You get a 3-second countdown (3.. 2.. 1.. GO!) to study the entire real maze.",
    "Đồng Hồ Chưa Tính Giờ:": "The Timer Is Paused:",
    "Thời gian 3 giây ghi nhớ không bị tính vào thời gian chơi. Tương tác vẽ bị khóa tạm thời.": "The 3-second memory window is not counted toward your play time, and drawing is locked during it.",
    "Không Có Bất Kỳ Số Manh Mối Nào:": "There Are No Clue Numbers At All:",
    "Sau khi tường ẩn, các ô sẽ trống trơn — bạn hoàn toàn phải dựa vào bộ nhớ của mình!": "Once the walls hide, cells go blank — you must rely purely on your memory!",
    "GHI NHỚ TRONG": "MEMORIZE IN",
    "GIÂY": "SECONDS",
    "TRONG 3 GIÂY ĐẦU": "IN THE FIRST 3 SECONDS",
    "TƯỜNG HIỆN": "WALLS SHOWN",
    "100% RÕ RÀNG": "100% CLEAR",
    "(Đồng hồ đứng yên)": "(Timer paused)",
    "ĐẶC BIỆT CHÚ Ý": "SPECIAL NOTE",
    "HOÀN TOÀN": "COMPLETELY",
    "KHÔNG CÓ SỐ": "NO NUMBERS",
    "Chỉ có ô S và F!": "Only the S and F cells remain!",
    "Tranh thủ 3 giây đếm ngược nhìn bao quát để khắc ghi đường thoát an toàn vào đầu!": "Use the 3-second countdown to scan the whole board and burn the safe escape route into your mind!",
    "Tường Biến Mất & Đi Bằng Trí Nhớ": "Walls Vanish & Walking From Memory",
    "QUY TẮC ĐI BẰNG TRÍ NHỚ": "MEMORY WALK RULES",
    "TIẾP THEO: DỰNG TƯỜNG NHÁP (3/3) ›": "NEXT: PLACE DRAFT WALLS (3/3) ›",
    "Mê Cung Ẩn Kín Hoàn Toàn:": "The Maze Hides Completely:",
    "Mọi bức tường đều biến mất. Bạn chỉ thấy ô Cầu thang Start (S) và Hố thang Finish (F).": "Every wall disappears. You only see the Start stair (S) and the Finish hole (F).",
    "Hậu Quả Khi Chạm Tường Vô Hình:": "Hitting An Invisible Wall:",
    "Ở chế độ Thường bạn sẽ bị đẩy về S và mất thời gian; ở chế độ Hardcore sẽ THUA NGAY LẬP TỨC!": "In Normal mode you get pushed back to S and lose time; in Hardcore you LOSE INSTANTLY!",
    "Vẽ Chậm Rãi Từng Bước Một:": "Draw Slowly, One Step At A Time:",
    "Đừng vội vàng kéo lướt qua nhiều ô. Hãy vừa đi vừa nhớ lại hình ảnh mê cung lúc nãy.": "Don't rush across many cells at once. Walk while replaying the maze image from your memory.",
    "GO!": "GO!",
    "BÀN CỜ SAU ĐÓ": "THE BOARD AFTERWARDS",
    "TRỐNG TRƠN": "COMPLETELY BLANK",
    "100% TƯỜNG ẨN": "100% WALLS HIDDEN",
    "Không còn vết tích!": "Not a single trace left!",
    "CẨN THẬN ĐÂM TƯỜNG": "CAREFUL OF HIDDEN WALLS",
    "CHẠM TƯỜNG ẨN": "TOUCH A HIDDEN WALL",
    "BỊ PHẠT VỀ S": "PENALTY: BACK TO S",
    "(Hardcore: Thua ngay)": "(Hardcore: instant loss)",
    "Đồng hồ bắt đầu tính giờ! Hãy vẽ chậm rãi và tái hiện lại trí nhớ của bạn.": "The timer starts now! Draw slowly and reconstruct the maze from memory.",
    "Dựng Tường Nháp & Gợi Ý": "Draft Walls & Hints",
    "BÍ QUYẾT CHIẾN THẮNG": "WINNING SECRETS",
    "ĐÃ HIỂU • THỬ THÁCH TRÍ NHỚ": "UNDERSTOOD • MEMORY CHALLENGE",
    "Xem lại từ đầu (Trang 1)": "Review from the start (Page 1)",
    "Dựng Tường Nháp Ngay Lập Tức:": "Place Draft Walls Immediately:",
    "Nối 2 điểm Anchor để đánh dấu các bức tường quan trọng bạn vừa thấy trước khi bộ nhớ bị phai.": "Connect 2 Anchors to mark the important walls you just saw before the memory fades.",
    "Tận Dụng Nút Gợi Ý Khi Bị Bí:": "Use The Hint Button When Stuck:",
    "Nếu quên hẳn khúc giữa, đừng liều đâm bừa; hãy bấm Gợi Ý để soi ra 1 ô an toàn.": "If a middle section slips away, don't gamble — tap Hint to reveal 1 safe cell.",
    "Rèn Luyện Trí Nhớ Mỗi Ngày:": "Train Your Memory Daily:",
    "Màn chơi càng rộng (4×4 rồi 5×5), số lượng tường càng nhiều, thử thách trí não đỉnh cao!": "Bigger boards (4×4 then 5×5) pack more walls for a top-tier brain challenge!",
    "CHIẾN THUẬT: VẼ TƯỜNG NHÁP": "TACTIC: DRAW DRAFT WALLS",
    "Nhanh Tay Khóa Khe Nguy Hiểm": "Quickly Lock Dangerous Gaps",
    "Vừa hết 3 giây, hãy dùng công cụ Ghi Nhớ": "The moment the 3 seconds end, use the Memory tool",
    "nối ngay các Anchor để dựng lại tường bạn nhớ.": "to reconnect the Anchors and rebuild the walls you remember.",
    "Giúp bạn không bị đãng trí giữa chừng!": "So you never blank out mid-run!",
    "GỢI Ý (HINT)": "HINT",
    "Soi lại đường an toàn": "Reveal the safe route",
    "Lỡ quên sạch đường đi?": "Forgot the whole route?",
    "Bấm Gợi Ý để soi sáng ngay": "Tap Hint to instantly light up",
    "1 đoạn đường đúng đắn tiếp theo.": "the next correct stretch of path.",
    "HOÀN TÁC (UNDO)": "UNDO",
    "Rút lại bước đi": "Take back a step",
    "Vừa đặt chân vào ô thấy sai sai?": "Stepped somewhere and got a bad feeling?",
    "Bấm Undo để lùi lại ô trước": "Tap Undo to back up one cell",
    "trước khi va phải tường ẩn!": "before you hit a hidden wall!",
    "Kẻ có trí nhớ tốt chưa chắc đã thắng — kẻ biết dùng Anchor dựng tường mới là cao thủ!": "A great memory alone won't win — the master is whoever rebuilds walls with Anchors!",
    # --------------------------------------------------------------- countdowncost
    "COUNTDOWN COST": "COUNTDOWN COST",
    "Ngân Sách & Giá Cước Ô": "Budget & Cell Tolls",
    "QUY TẮC CHI PHÍ BƯỚC": "STEP COST RULES",
    "TIẾP THEO: ĐÂM TƯỜNG TRỪ CƯỚC (2/3) ›": "NEXT: WALL HITS CHARGE THE TOLL (2/3) ›",
    "Bỏ qua hướng dẫn & Vào tính cước ngay": "Skip guide & start counting the cost now",
    "NGÂN SÁCH & CƯỚC": "BUDGET & TOLLS",
    "ĐÂM TƯỜNG TRỪ BƯỚC": "WALL HITS COST STEPS",
    "TỐI ƯU CHI PHÍ": "OPTIMIZE COST",
    "Con Số Là Chi Phí Bước Của Ô:": "The Number Is The Cell's Step Cost:",
    "Mỗi khi bạn bước vào ô nào, ngân sách sẽ trừ thẳng bấy nhiêu bước (từ 1 đến 4 bước).": "Every cell you enter charges its price straight from your budget (1 to 4 steps).",
    "Ngân Sách Tụt Về 0 Là Thua Ngay:": "Budget Drops To 0 And You Lose:",
    "Nếu chưa kịp chạm tới hố thang Finish mà đã cạn kiệt ngân sách bước • Game Over!": "If the step budget runs dry before you reach the Finish hole • Game Over!",
    "Không Liên Quan Tới Số Tường:": "Nothing To Do With Wall Counts:",
    "Con số ở chế độ này hoàn toàn không báo vị trí tường — chỉ biểu thị chi phí bước đi.": "Numbers here never mark walls — they only show the step cost of walking through.",
    "NGÂN SÁCH CÒN:": "BUDGET LEFT:",
    "ĐÃ TIÊU: -3 BƯỚC (QUA 2 Ô)": "SPENT: -3 STEPS (2 CELLS)",
    "Ô GIÁ RẺ (1 - 2)": "CHEAP CELLS (1 - 2)",
    "TIẾT KIỆM": "SAVINGS",
    "Ưu tiên đi qua": "Route through these",
    "để giữ ngân sách!": "to protect your budget!",
    "Ô GIÁ ĐẮT (3 - 4)": "PRICEY CELLS (3 - 4)",
    "TỐN KÉM!": "EXPENSIVE!",
    "Đi 1 ô số 4 bằng": "One step into a 4 costs",
    "4 lần ô số 1!": "as much as four 1s!",
    "Đã đi qua 2 ô: Ô [1] + Ô [2] • Tổng cước: -3 bước, ngân sách còn 13 bước!": "Walked 2 cells: [1] + [2] • Total toll: -3 steps, leaving 13 steps in the budget!",
    "Đâm Tường & Bẫy Ô Đắt": "Wall Hits & Pricey-Cell Traps",
    "QUY TẮC ĐÂM TƯỜNG & CƯỚC PHÍ": "WALL HIT & TOLL RULES",
    "TIẾP THEO: TỐI ƯU CHI PHÍ & UNDO (3/3) ›": "NEXT: OPTIMIZE COST & UNDO (3/3) ›",
    "Đâm Tường Vẫn Bị Phạt Cước Bước:": "Wall Hits Still Charge The Toll:",
    "Đâm vào tường vô hình sẽ văng về S và trừ thẳng chi phí của ô bạn vừa toan bước vào.": "Hitting an invisible wall bounces you back to S and charges the cost of the cell you tried to enter.",
    "Hạn Chế Bước Vào Ô Số 3 & Số 4:": "Avoid Cells 3 & 4:",
    "Chỉ 2-3 ô số to là đủ vét sạch ngân sách của bạn. Hãy ưu tiên các tuyến đường qua ô 1 và 2.": "Just 2-3 big cells can wipe your entire budget. Prefer routes through cells 1 and 2.",
    "Tường Lộ Ra Để Rút Kinh Nghiệm:": "Walls Reveal Themselves As Lessons:",
    "Bức tường bị đâm sẽ hiện rõ trên bàn cờ. Đừng đâm lại lần thứ hai làm tiêu hao ngân sách!": "The wall you hit stays visible on the board. Don't hit it twice and burn more budget!",
    "HẬU QUẢ ĐÂM TƯỜNG": "RESULT OF A WALL HIT",
    "VẪN TRỪ -3 BƯỚC!": "STILL -3 STEPS!",
    "Bị phạt đúng giá cước": "You pay the exact toll",
    "của ô bạn vừa đâm!": "of the cell you rammed into!",
    "CẨN THẬN BẪY Ô ĐẮT": "BEWARE OF PRICEY TRAPS",
    "Ô SỐ 3 & SỐ 4": "CELLS 3 & 4",
    "Hao hụt ngân sách cực nhanh.": "They drain the budget fast.",
    "Nên tìm đường né tránh!": "Try to route around them!",
    "Đâm tường ở Countdown Cost bị phạt kép: vừa văng về S, vừa mất đứt số bước của ô đích!": "Wall hits in Countdown Cost punish twice: back to S, plus the cost of the target cell!",
    "Tối Ưu Chi Phí & Hoàn Cước": "Optimize Cost & Undo Refunds",
    "BÍ QUYẾT PHÁ ĐẢO": "ISLAND-CLEARING SECRETS",
    "ĐÃ HIỂU • TỐI ƯU NGÂN SÁCH": "UNDERSTOOD • OPTIMIZE THE BUDGET",
    "Tìm Tuyến Đường Rẻ Nhất Trước Khi Vẽ:": "Scout The Cheapest Route First:",
    "Nhẩm tính tổng số điểm của các ô trên đường đi; chọn nhánh có tổng số nhỏ nhất để tới F.": "Add up the cell values along each route; pick the branch with the smallest total to reach F.",
    "Tận Dụng Undo Để Thu Hồi Ngân Sách:": "Use Undo To Reclaim Budget:",
    "Nếu nhận thấy nhánh đang đi quá tốn bước, hãy Undo lùi lại để nhận lại toàn bộ số bước đã trừ.": "If a branch turns out too costly, Undo back and recover every step already spent.",
    "Xếp Hạng Dựa Trên Chi Phí Tối Thiểu:": "Ranking Rewards Minimum Cost:",
    "Người chơi về đích với tổng chi phí bước tiêu tốn càng ít sẽ giành thứ hạng càng cao!": "The fewer steps you burn on the way to the exit, the higher you rank!",
    "BÍ QUYẾT: ĐƯỜNG RẺ NHẤT": "TACTIC: THE CHEAPEST PATH",
    "CƯỚC: 6 BƯỚC • DƯ 10": "COST: 6 STEPS • 10 LEFT",
    "CƯỚC: 17 BƯỚC • THUA": "COST: 17 STEPS • LOSS",
    "Ngân Sách Luôn Đủ Cho Đường Rẻ": "The Budget Always Fits The Cheap Route",
    "Mỗi màn đều cấp đủ số bước cho": "Every level grants enough steps for",
    "tuyến đường ít tốn kém nhất + dự phòng.": "the cheapest route plus a buffer.",
    "Đi lệch qua ô đắt sẽ bị cạn sạch bước!": "Stray into pricey cells and the steps run dry!",
    "HOÀN TRẢ CƯỚC 100%": "100% TOLL REFUND",
    "+HOÀN LẠI SỐ BƯỚC ĐÃ TRỪ!": "+EVERY SPENT STEP COMES BACK!",
    "Lỡ bước vào ô đắt đỏ hoặc muốn đổi hướng?": "Stepped into an expensive cell or want to turn around?",
    "Bấm Undo lùi lại, số bước bị trừ sẽ lập tức cộng ngược lại vào ngân sách.": "Tap Undo and every charged step is instantly refunded to your budget.",
    "Đừng tiếc một lần Undo! Lùi lại để chọn lối đi rẻ hơn sẽ cứu sống cả ván đấu.": "Never regret an Undo! Backing up to a cheaper route can save the whole run.",
    # ---------------------------------------------------------------------- dungeon
    "CHẾ ĐỘ VÔ TẬN": "ENDLESS MODE",
    "Leo Tầng & Quản Lý Bước": "Floor Climbing & Step Management",
    "LUẬT CHƠI VÔ TẬN": "ENDLESS RUN RULES",
    "TIẾP THEO: CƠ CHẾ ĐÂM TƯỜNG (2/3) ›": "NEXT: WALL HIT MECHANICS (2/3) ›",
    "Bỏ qua hướng dẫn & Vào leo tầng ngay": "Skip guide & start climbing now",
    "QUẢN LÝ BƯỚC": "STEP MANAGEMENT",
    "ĐÂM TƯỜNG VỀ S": "WALL HITS SEND TO S",
    "BẪY VÔ TẬN": "ENDLESS TRAPS",
    "Chế Độ Duy Nhất Giới Hạn Bước Đi:": "The Only Mode With A Step Limit:",
    "Mỗi ô di chuyển trừ 1 bước. Tuyệt đối không để số bước tụt về 0!": "Each move costs 1 step. Never let your step count hit 0!",
    "Nhận Thêm Bước Thưởng Khi Qua Tầng:": "Bonus Steps For Clearing A Floor:",
    "Xuống được hố thang F sẽ cộng thêm bước cho tầng kế tiếp và tích lũy điểm số.": "Descending the F shaft grants extra steps for the next floor and banks your score.",
    "Chinh Phục Kỷ Lục Tầng Sâu Nhất:": "Chase The Deepest-Floor Record:",
    "Game không có màn cuối! Hãy bảo toàn tối đa số bước để đi xa nhất có thể.": "There is no final level! Preserve as many steps as you can and go as deep as possible.",
    "SỐ BƯỚC CÒN LẠI": "STEPS REMAINING",
    "BƯỚC": "STEPS",
    "TẦNG HIỆN TẠI": "CURRENT FLOOR",
    "THỜI GIAN": "TIME",
    "MỖI BƯỚC ĐI": "EVERY MOVE",
    "-1 BƯỚC": "-1 STEP",
    "Hết bước = THUA": "Out of steps = LOSS",
    "CHẠM HỐ ĐÍCH F": "REACH THE F SHAFT",
    "+5 BƯỚC!": "+5 STEPS!",
    "Xuống Tầng 05": "Descend To Floor 05",
    "Đi đường càng ngắn thì bước dư càng nhiều để chinh phục các tầng sâu hơn!": "Shorter routes leave more spare steps for conquering deeper floors!",
    "Đâm Tường & Lộ Tường Thật": "Wall Hits & Real Walls Revealed",
    "QUY TẮC ĐÂM TƯỜNG": "WALL HIT RULES",
    "TIẾP THEO: BẪY VÔ TẬN & MẸO LEO SÂU (3/3) ›": "NEXT: ENDLESS TRAPS & DEEP-CLIMB TIPS (3/3) ›",
    "Không Bị Game Over Ngay Lập Tức:": "No Instant Game Over:",
    "Đâm tường vô hình ở Dungeon không kết thúc màn chơi, chỉ trừ 1 bước di chuyển.": "Hitting an invisible wall in Dungeon doesn't end the run — it only costs 1 step.",
    "Bức Tường Sẽ Lộ Diện Vĩnh Viễn:": "The Wall Stays Revealed Forever:",
    "Vách tường bạn vừa đâm vào sẽ hiện thành nét đen đậm rõ ràng suốt tầng đó.": "The wall you hit turns into a bold dark line for the rest of that floor.",
    "Văng Ngược Về Cầu Thang Xuất Phát (S):": "Bounced Back To The Start Stair (S):",
    "Nhân vật trở lại điểm S để bắt đầu đường vẽ mới né tránh đoạn tường vừa biết.": "Your piece returns to S to start a fresh line that avoids the wall you just learned about.",
    "TƯỜNG THẬT ĐÃ LỘ!": "A REAL WALL REVEALED!",
    "Nét đen đậm": "A bold dark line",
    "Không biến mất": "that never fades",
    "HẬU QUẢ VA CHẠM": "IMPACT RESULT",
    "-1 BƯỚC ĐI": "-1 STEP",
    "Văng ngược về S": "Bounced back to S",
    "Đừng sợ đâm tường! Đâm tường là cách hy sinh 1 bước để bản đồ lộ ra manh mối thật.": "Don't fear wall hits! Trading 1 step is how the map reveals its real clues.",
    "Bẫy Vô Tận & Mẹo Sinh Tồn": "Endless Traps & Survival Tips",
    "BÍ QUYẾT LEO SÂU": "DEEP CLIMB SECRETS",
    "ĐÃ HIỂU • BẮT ĐẦU LEO TẦNG": "UNDERSTOOD • START CLIMBING",
    "Tường Gợi Ý Giảm Về 0%:": "Pre-Drawn Walls Fade To 0%:",
    "Càng xuống sâu tường càng ẩn kín, đòi hỏi tính toán cẩn thận từng con số.": "The deeper you go, the more hidden the walls — every number demands careful thought.",
    "Luôn Đánh Dấu Tường Nghi Ngờ:": "Always Mark Suspected Walls:",
    "Dùng công cụ Ghi Nhớ nối 2 điểm neo để khóa các khe nguy hiểm trước khi vẽ.": "Use the Memory tool to connect 2 anchor points and lock dangerous gaps before drawing.",
    "Hồi Sinh Tại Chỗ (+3 Bước):": "Revive On The Spot (+3 Steps):",
    "Khi cạn bước, hồi sinh sẽ cộng +3 bước và giữ nguyên 100% mê cung & tường đã lộ!": "When steps run out, revive grants +3 steps while keeping 100% of the maze & revealed walls!",
    "TẦNG ĐẦU (TẦNG 1 - 3)": "EARLY FLOORS (1 - 3)",
    "CÒN TƯỜNG VẼ SẴN": "PRE-DRAWN WALLS REMAIN",
    "Dễ hình dung lối thoát": "Easier to picture the way out",
    "Tỉ lệ tường lộ: 40% ~ 60%": "Wall reveal ratio: 40% ~ 60%",
    "TẦNG SÂU (TẦNG 5 TRỞ ĐI)": "DEEP FLOORS (5 AND BEYOND)",
    "100% TƯỜNG VÔ HÌNH!": "100% INVISIBLE WALLS!",
    "Dùng Ghi Nhớ nối Anchor": "Use Memory to link Anchors",
    "để tự dựng tường nháp trước": "and build draft walls first",
    "Càng lên cao tường sẵn càng biến mất — hãy nối Anchor trước khi đặt bút vẽ đường!": "The deeper you go the fewer free walls you get — link Anchors before you draw!",
    # ------------------------------------------------------------------- fadingink
    "FADING INK • MỰC PHAI": "FADING INK",
    "Cơ Chế Phai Mực Toàn Bàn": "Whole-Board Ink Fading",
    "QUY TẮC MỰC PHAI CƠ BẢN": "BASIC INK FADING RULES",
    "TIẾP THEO: Ô CẠN KHÓA ĐƯỜNG (2/3) ›": "NEXT: DRY CELLS BLOCK THE WAY (2/3) ›",
    "Bỏ qua hướng dẫn & Vào chơi ngay": "Skip guide & start playing now",
    "MỖI BƯỚC -1 MỰC": "EACH MOVE: -1 INK",
    "Ô CẠN KHÓA ĐƯỜNG": "DRY CELLS BLOCK PATHS",
    "ĐƯỜNG TỐI ƯU & UNDO": "OPTIMAL PATH & UNDO",
    "Số Trên Ô Thể Hiện Lượng Mực Còn Lại:": "The Number Shows Remaining Ink:",
    "Mỗi ô có điểm mực riêng. Chỉ được phép bước vào các ô vẫn CÒN mực (> 0).": "Every cell has its own ink. You may only step into cells that STILL have ink (> 0).",
    "Cả Bàn Cờ Cùng Phai Đi Một Nhịp:": "The Whole Board Fades One Tick:",
    "Mỗi bước bạn di chuyển, TẤT CẢ các ô đều bị trừ 1 mực, bất kể bạn có đi vào ô đó hay không!": "Every step you take drains 1 ink from EVERY cell — whether you enter it or not!",
    "Hoàn Toàn Không Có Bức Tường Nào:": "There Are No Walls At All:",
    "Bàn cờ thông suốt; chướng ngại vật cản đường bạn duy nhất chính là các ô bị cạn sạch mực.": "The board is wide open; the only obstacles are cells whose ink has run dry.",
    "CÒN 1": "1 LEFT",
    "SỐ TRÊN Ô LÀ": "THE NUMBER IS",
    "ĐIỂM MỰC": "INK POINTS",
    "Không phải số tường!": "Not a wall count!",
    "Không phải bom!": "Not a bomb count!",
    "-1 MỰC": "-1 INK",
    "Tất cả các ô trên": "Every cell on",
    "bàn cờ cùng phai!": "the board fades too!",
    "Bạn đi được 3 bước = Toàn bộ các ô trên bàn cờ đều bị phai mất 3 điểm mực!": "Walk 3 steps = every cell on the board loses 3 ink!",
    "Ô Cạn Khóa Lối & Cảnh Báo": "Dry Cells Block Paths & Warnings",
    "QUY TẮC CẠN MỰC & KHÓA ĐƯỜNG": "DRY INK & BLOCKED PATH RULES",
    "TIẾP THEO: ĐƯỜNG NGẮN NHẤT & UNDO (3/3) ›": "NEXT: SHORTEST PATH & UNDO (3/3) ›",
    "Cảnh Báo Ô Viền Cam (Còn 1 Mực):": "Orange-Rimmed Cells (1 Ink Left):",
    "Ô này chỉ tồn tại thêm đúng 1 lượt đi nữa. Nếu bạn không bước vào ngay, nó sẽ cạn sạch.": "This cell survives exactly one more move. Step in now or it runs completely dry.",
    "Ô Về 0 Biến Thành Khoảng Trống Bị Khóa:": "0-Ink Cells Become Locked Gaps:",
    "Mất hoàn toàn con số và mờ đi. Người chơi bị chặn không thể bước chân vào ô cạn mực.": "The number vanishes and the cell greys out. You are blocked from entering a dry cell.",
    "Thua Cuộc Khi Bị Bít Lối Đi:": "You Lose When Every Route Is Sealed:",
    "Nếu các ô xung quanh đều cạn mực và không còn lối nào tới hố thang F • HẾT ĐƯỜNG ĐI!": "If every surrounding cell is dry and no route to the F shaft remains • DEAD END!",
    "Ô CÒN 1 ĐIỂM MỰC": "CELL WITH 1 INK LEFT",
    "SẮP PHAI": "ALMOST FADED",
    "CÒN ĐÚNG 1 BƯỚC!": "EXACTLY 1 MOVE LEFT!",
    "Nếu đi thêm 1 bước nữa vào": "Take one more step into",
    "bất kỳ đâu, ô này sẽ biến mất!": "anywhere and this cell vanishes!",
    "Ô 0 MỰC: BỊ KHÓA": "0-INK CELL: LOCKED",
    "CẠN": "DRY",
    "KHÔNG THỂ BƯỚC VÀO": "CANNOT ENTER",
    "Ô trở thành khoảng trống rỗng.": "The cell becomes an empty gap.",
    "Bị bít hết đường = THUA NGAY!": "Every route sealed = INSTANT LOSS!",
    "Hãy để ý các ô viền cam! Chúng báo trước những lối đi sắp biến mất vĩnh viễn.": "Watch the orange-rimmed cells! They warn about paths that are about to vanish forever.",
    "Đường Ngắn & Hồi Mực": "Shortest Path & Ink Recovery",
    "ĐÃ HIỂU • BẮT ĐẦU VẼ ĐƯỜNG": "UNDERSTOOD • START DRAWING",
    "Tìm Đường Ngắn Nhất Trước Khi Vẽ:": "Plan The Shortest Path First:",
    "Nhìn bao quát bàn cờ, đếm số bước tới F và chọn tuyến đường ít ô chuyển hướng nhất.": "Scan the board, count the steps to F and pick the route with the fewest turns.",
    "Tận Dụng Undo Để Hồi Phục Đường Đi:": "Use Undo To Restore The Path:",
    "Lỡ đi vào ngõ cụt làm ô phía trước biến mất? Undo ngay để cứu lại mực cho các ô đó.": "Wandered into a dead end and lost the cells ahead? Undo to give that ink back.",
    "Đồng Hồ Thời Gian Vẫn Tính Điểm:": "The Clock Still Counts:",
    "Chế độ này không giới hạn số bước, nhưng hoàn thành càng nhanh thì điểm xếp hạng càng cao!": "This mode has no step limit, but the faster you finish, the higher you rank!",
    "BÍ QUYẾT: ĐƯỜNG NGẮN NHẤT": "TACTIC: SHORTEST PATH",
    "4 BƯỚC • THẮNG": "4 STEPS • WIN",
    "7 BƯỚC • CẠN MỰC": "7 STEPS • DRY INK",
    "Đường Ngắn Luôn Đủ Mực": "The Short Route Always Has Enough Ink",
    "Mỗi màn đều được thiết kế sao cho": "Every level is designed so that",
    "đường ngắn nhất có đủ mực để tới F.": "the shortest path has enough ink to reach F.",
    "Đi vòng vèo sẽ tự làm cạn mực bít đường!": "Wandering around drains the ink and seals your own path!",
    "ĐẶC QUYỀN HỒI MỰC": "INK RESTORE PERK",
    "+1 MỰC CHO TOÀN BÀN CỜ!": "+1 INK FOR THE WHOLE BOARD!",
    "Mỗi lần bấm Undo lùi 1 bước chân, tất cả": "Each Undo rewinds 1 step, and every",
    "các ô trên bàn cờ đều được hồi phục lại đúng 1 điểm mực.": "cell on the board regains exactly 1 ink point.",
    "Đừng ngại Undo! Rút lại bước đi sẽ hồi sinh ngay các ô vừa bị cạn mực.": "Don't hold back on Undo! Rewinding a step instantly revives cells that just ran dry.",
    # ------------------------------------------------------------------ fog_of_war
    "FOG OF WAR • SƯƠNG MÙ": "FOG OF WAR",
    "Màn Sương & Tầm Nhìn 1 Ô": "The Fog & 1-Cell Vision",
    "QUY TẮC MÀN SƯƠNG": "FOG RULES",
    "TIẾP THEO: DÒ ĐƯỜNG TỪNG BƯỚC (2/3) ›": "NEXT: SCOUTING STEP BY STEP (2/3) ›",
    "Bỏ qua hướng dẫn & Vào dò đường ngay": "Skip guide & start scouting now",
    "TẦM NHÌN BÁN KÍNH 1": "RADIUS-1 VISION",
    "DÒ ĐƯỜNG TỪNG BƯỚC": "SCOUT STEP BY STEP",
    "GHI NHỚ & BÍ QUYẾT": "MEMORY & TIPS",
    "Chỉ Thấy Số Trong Bán Kính 1 Ô:": "Only Numbers Within 1 Cell Show:",
    "Bạn chỉ có thể đọc được manh mối số của các ô nằm ngay sát cạnh (ngang, dọc, chéo).": "You can only read clue numbers from cells directly beside you (horizontal, vertical, diagonal).",
    "Các Ô Ở Xa Bị Phủ Mờ Hoàn Toàn:": "Distant Cells Stay Fully Fogged:",
    "Màn sương mù ẩn giấu toàn bộ con số của những ô phía xa cho đến khi bạn bước lại gần.": "The fog hides every number on far cells until you walk close enough.",
    "Tường Vô Hình Vẫn Nằm Ẩn Mình:": "Invisible Walls Still Lurk:",
    "Vẫn có các bức tường vô hình giữa các ô — bước bừa vào sương mù là đâm tường ngay!": "Invisible walls still sit between cells — step blindly into the fog and you hit one!",
    "VÙNG TẦM NHÌN": "VISION ZONE",
    "BÁN KÍNH 1 Ô": "RADIUS 1 CELL",
    "HIỆN RÕ SỐ": "NUMBERS SHOW",
    "Chỉ thấy ô sát cạnh bạn!": "Only cells right beside you!",
    "VÙNG SƯƠNG MÙ": "FOG ZONE",
    "Ô Ở XA BẠN": "CELLS FAR AWAY",
    "ẨN CON SỐ": "NUMBERS HIDDEN",
    "Che khuất manh mối!": "Clues are masked!",
    "Bạn đi đến đâu thì quầng sáng mở ra tới đó — ô ở xa sẽ bị sương mù che mất số!": "The glow opens up wherever you walk — distant cells keep their numbers hidden in fog!",
    "Dò Đường Theo Bước Chân": "Scouting With Every Step",
    "QUY TẮC DI CHUYỂN TRONG SƯƠNG": "MOVING THROUGH THE FOG",
    "TIẾP THEO: GHI NHỚ ANCHOR & BÍ QUYẾT (3/3) ›": "NEXT: ANCHOR MEMORY & TIPS (3/3) ›",
    "Tầm Nhìn Di Chuyển Theo Từng Bước:": "Vision Moves With Every Step:",
    "Đặt chân tới ô mới sẽ lập tức hé lộ con số của những ô tiếp giáp phía trước mặt bạn.": "Stepping onto a new cell instantly reveals the numbers of the cells touching your front.",
    "Ô Cũ Phía Sau Sẽ Bị Che Lại:": "Cells Behind You Get Re-Fogged:",
    "Các ô ở xa tầm nhìn sẽ bị sương mù bao phủ trở lại, khiến bạn khó nhìn lại số cũ.": "Cells beyond your vision are swallowed by fog again, so old numbers are hard to recheck.",
    "Nguy Cơ Va Phải Tường Vô Hình:": "Risk Of Hitting Invisible Walls:",
    "Nếu bước liều sang ô chưa sáng, bạn có thể đâm trúng tường ẩn và bị phạt văng về điểm S!": "Dare to step into an unlit cell and you may ram a hidden wall and get bounced back to S!",
    "Ô ĐÃ BƯỚC QUA": "CELL ALREADY VISITED",
    "MỜ DẦN ĐI": "FADING OUT",
    "ẨN LẠI SỐ": "NUMBER HIDDEN AGAIN",
    "Sương mù phủ lại!": "The fog rolls back in!",
    "BẪY TƯỜNG ẨN": "HIDDEN WALL TRAP",
    "ĐÂM VÀO TƯỜNG": "WALL HIT",
    "Bước tới đâu sương mù mở tới đó — nhưng tuyệt đối không bước bừa vào ô chưa rõ số!": "The fog parts wherever you go — but never step blindly into a cell whose number is unknown!",
    "Ghi Nhớ Anchor & Bí Quyết": "Anchor Memory & Secrets",
    "ĐÃ HIỂU • VƯỢT MÀN SƯƠNG": "UNDERSTOOD • BEAT THE FOG",
    "Dựng Tường Nháp Ngay Khi Quầng Sáng Soi Thấy:": "Place Draft Walls While The Glow Shows:",
    "Đừng để sương mù che khuất manh mối. Nối 2 Anchor để đánh dấu tường cam bảo vệ bản thân.": "Don't let fog hide the clues. Connect 2 Anchors to mark orange walls and protect yourself.",
    "Bật Đèn Bằng Nút Gợi Ý:": "Light The Path With Hint:",
    "Khi rơi vào ngõ cụt và không đoán được bước tiếp theo, hãy dùng Gợi Ý để soi ra 1 ô đúng.": "Stuck in a dead end? Tap Hint to reveal 1 correct cell.",
    "Tiến Lên Từng Ô Một Cách Chắc Chắn:": "Advance One Certain Cell At A Time:",
    "Chế độ này không giới hạn số bước. Cứ bình tĩnh suy luận từng ô để đưa lối thoát về hố thang F!": "No step limit here. Reason calmly cell by cell and bring the route home to the F shaft!",
    "CHIẾN THUẬT: KHÓA TƯỜNG ANCHOR": "TACTIC: LOCK WALLS WITH ANCHORS",
    "Khóa Tường Trước Khi Sương Mù Che Mất": "Lock Walls Before The Fog Hides Them",
    "Thấy ô có số 2? Hãy nối ngay 2 Anchor": "See a 2? Instantly connect 2 Anchors",
    "để dựng vách tường cam bảo vệ.": "to raise an orange wall for cover.",
    "Tường bạn tự vẽ KHÔNG bị sương mù xóa!": "Walls you draw are NEVER erased by fog!",
    "Soi đường trong tối": "Light the way in the dark",
    "Mất phương hướng trong sương?": "Losing your bearings in the fog?",
    "1 đoạn đường an toàn phía trước.": "the next safe stretch of path ahead.",
    "Bước vào hướng thấy nguy hiểm?": "Stepped into a direction that feels wrong?",
    "Bấm Undo để lùi lại ô an toàn": "Tap Undo to retreat to a safe cell",
    "trước khi đâm vào tường ẩn!": "before ramming a hidden wall!",
    "Kẻ mù quáng bước đi sẽ đâm tường — người biết dùng Anchor khóa lối sẽ chiến thắng!": "Blind steppers hit walls — whoever locks routes with Anchors wins!",
    # ---------------------------------------------------------------- minesweeper
    "MINESWEEPER MAZE": "MINESWEEPER MAZE",
    "Luật Dò Mìn 8 Ô": "8-Neighbor Mine Rules",
    "QUY TẮC DÒ MÌN CƠ BẢN": "BASIC MINESWEEPER RULES",
    "TIẾP THEO: ĐẠP BOM & VÙNG SỐ 0 (2/3) ›": "NEXT: BOMBS & ZERO ZONES (2/3) ›",
    "Bỏ qua hướng dẫn & Vào dò mìn ngay": "Skip guide & start sweeping now",
    "LUẬT 8 Ô BOM": "8-NEIGHBOR BOMB RULE",
    "ĐẠP BOM & VÙNG 0": "BOMBS & ZERO ZONES",
    "CÔNG CỤ DÒ BOM": "BOMB-SWEEPING TOOLS",
    "Số Trên Ô = Số Bom Trong 8 Ô Lân Cận:": "The Number = Bombs In The 8 Neighbor Cells:",
    "Bao gồm 4 ô vuông góc (trên, dưới, trái, phải) và 4 ô góc chéo xung quanh.": "That includes the 4 orthogonal cells (up, down, left, right) and the 4 diagonal corners.",
    "Cầu Thang Start (S) & Finish (F) Luôn An Toàn:": "Start Stair (S) & Finish (F) Are Always Safe:",
    "Ô xuất phát và hố thang đích 100% không có bom. Luôn có đường BFS không bom tới đích!": "The start cell and the finish shaft are 100% bomb-free. A bomb-free route to the exit always exists!",
    "Không Có Bất Kỳ Vách Tường Nào:": "There Are No Walls At All:",
    "Không có tường cản bước — bạn có thể đi tự do nhưng chỉ được bước vào ô sạch bom.": "No walls block your steps — move freely, but only into bomb-free cells.",
    "CON SỐ Ở GIỮA": "THE NUMBER IN THE CENTER",
    "SỐ 1 = 1 BOM": "A 1 = 1 BOMB",
    "Trong 8 ô xung quanh": "Among the 8 surrounding cells",
    "(tính cả góc chéo!)": "(diagonals included!)",
    "VỊ TRÍ CÓ BOM": "A BOMB IS HERE",
    "TRÁNH XA!": "STAY AWAY!",
    "Đạp trúng bom": "Stepping on a bomb",
    "= THUA NGAY": "= INSTANT LOSS",
    "Khác với mê cung thường: Số chỉ bom trong 8 ô lân cận (ngang, dọc VÀ chéo)!": "Unlike normal mazes: the number counts bombs in the 8 neighboring cells (horizontal, vertical AND diagonal)!",
    "Đạp Bom Nổ & Vùng Số 0": "Bomb Detonation & Zero Zones",
    "CHIẾN THUẬT DÒ ĐƯỜNG": "PATH-SCOUTING TACTICS",
    "TIẾP THEO: CÔNG CỤ DÒ BOM & CẮM CỜ (3/3) ›": "NEXT: TOOLS & FLAGGING (3/3) ›",
    "Hậu Quả Khi Đạp Trúng Bom:": "Stepping On A Bomb:",
    "Ván đấu dừng ngay tức khắc. Bạn đứng tại ô nổ và có thể hồi sinh lùi lại 1 bước.": "The run stops immediately. You stand on the blast cell and can revive one step back.",
    "Tận Dụng Triệt Để Các Ô Số 0:": "Exploit Zero Cells To The Fullest:",
    "Nếu ô có số 0, toàn bộ 8 ô kề cạnh nó 100% không có bom — hãy đi qua vùng này!": "If a cell shows 0, all 8 cells around it are 100% bomb-free — route through that zone!",
    "Kéo Nét Vẽ Chậm Rãi:": "Draw Your Line Slowly:",
    "Không vội vàng kéo lướt nhanh; chỉ vẽ vào các ô bạn đã chắc chắn an toàn.": "Don't swipe fast; only draw into cells you are certain are safe.",
    "ĐẠP PHẢI BOM": "STEPPED ON A BOMB",
    "THUA NGAY TẠI CHỖ!": "INSTANT LOSS ON THE SPOT!",
    "Nhân vật dừng ngay tại ô nổ": "Your piece stops on the blast cell",
    "(Không văng về S như Dungeon)": "(no bounce back to S like Dungeon)",
    "VÙNG Ô SỐ 0": "THE ZERO ZONE",
    "CẢ 8 Ô ĐỀU SẠCH BOM!": "ALL 8 CELLS ARE BOMB-FREE!",
    "Tự tin bước qua bất kỳ ô nào": "Confidently step onto any cell",
    "đang tiếp giáp với ô số 0": "that touches a 0 cell",
    "Hãy tìm các ô số 0 trước tiên — đó là chìa khóa mở toang lối đi an toàn!": "Hunt for 0 cells first — they are the key that flings open a safe path!",
    "Công Cụ & HUD Đếm Bom": "Tools & The Bomb-Count HUD",
    "ĐÃ HIỂU • BẮT ĐẦU DÒ MÌN": "UNDERSTOOD • START SWEEPING",
    "Cắm Cờ Trước Khi Vẽ Đường:": "Flag Before You Draw:",
    "Khi phát hiện ô chắc chắn có bom, hãy cắm cờ khóa ô lại ngay để tránh tay quẹt trúng.": "When a cell is certain to hold a bomb, flag it right away so a swipe can't touch it.",
    "Kiểm Tra Tổng Số Bom Trên HUD:": "Check The Bomb Total On The HUD:",
    "Đối chiếu số cờ đã cắm với số bom còn lại trên HUD để đảm bảo không bỏ sót quả nào.": "Cross-check your flags against the HUD's remaining bombs so none slip past.",
    "Hồi Sinh Rút Lại Bước Lỗi:": "Revive To Take Back The Bad Step:",
    "Nếu lỡ đạp trúng bom, bạn có thể hồi sinh để quay lại ô ngay trước đó và thử hướng khác.": "If you step on a bomb, revive to return to the previous cell and try another direction.",
    "BOM CÒN LẠI TRÊN BÀN": "BOMBS LEFT ON THE BOARD",
    "Đã phát hiện 2 quả • Còn 3 quả ẩn giấu": "2 found • 3 still hidden",
    "CẮM CỜ KHÓA Ô": "FLAG A CELL LOCKED",
    "Chống bấm nhầm": "Guards against mis-taps",
    "Dùng nút Ghi Nhớ để cắm cờ": "Use the Memory button to flag",
    "vào ô bạn nghi là có bom.": "cells you suspect of hiding bombs.",
    "Ô cắm cờ sẽ bị khóa an toàn!": "A flagged cell is safely locked!",
    "HOÀN TÁC": "UNDO",
    "Lùi 1 bước an toàn": "Back up 1 step safely",
    "Lỡ bước nhầm ô nguy hiểm?": "Stepped into a dangerous cell?",
    "Bấm Undo để lùi lại ngay lập tức": "Tap Undo to instantly back out",
    "trước khi dẫn đến sai lầm.": "before it turns into a mistake.",
    "Luôn để mắt tới thẻ HUD Bom để biết mình đã cô lập hết bom trên bàn chưa!": "Keep an eye on the Bomb HUD card to know when every bomb is isolated!",
    # ---------------------------------------------------------------- normal_maze
    "HƯỚNG DẪN CHƠI": "HOW TO PLAY",
    "Cách Vượt Mê Cung": "Clearing The Maze",
    "QUY TẮC CẦN NHỚ": "RULES TO REMEMBER",
    "TIẾP THEO: MANH MỐI SỐ (2/3) ›": "NEXT: NUMBER CLUES (2/3) ›",
    "BẮT ĐẦU & ĐÍCH": "START & FINISH",
    "MANH MỐI SỐ": "NUMBER CLUES",
    "CÔNG CỤ": "TOOLS",
    "Nối Cầu Thang Xuất Phát tới Hố Đích:": "Connect The Start Stair To The Finish Hole:",
    "Đặt ngón tay vào tâm ô Cầu Thang S, kéo liên tục qua các ô để vẽ đường.": "Touch the center of the S stair cell, then keep dragging across cells to draw your line.",
    "Cảnh giác Tường Vô Hình:": "Beware Invisible Walls:",
    "Đâm phải tường ẩn giữa 2 ô sẽ bị Game Over ngay lập tức!": "Hitting a hidden wall between 2 cells ends the run instantly!",
    "Dựa vào manh mối các con số:": "Lean On The Number Clues:",
    "Con số trên ô cho biết số cạnh xung quanh có tường (xem tiếp ở Trang 2).": "A cell's number tells how many of its sides hide walls (more on Page 2).",
    "XUẤT PHÁT": "START",
    "Cầu thang rọi sáng": "A stair that lights the way",
    "HỐ ĐÍCH (F)": "FINISH HOLE (F)",
    "Thang xuống sâu": "The shaft that leads down",
    "KÉO NỐI TÂM Ô": "DRAG BETWEEN CELL CENTERS",
    "Bắt đầu từ Cầu Thang Trên Lầu • Đi theo đường an toàn • Xuống Hố Thang Đích": "Start at the Upstairs Stair • Follow the safe path • Down to the Finish Shaft",
    "Manh Mối Con Số": "Number Clues",
    "QUY TẮC CON SỐ": "NUMBER RULES",
    "TIẾP THEO: CÁC CÔNG CỤ HỖ TRỢ (3/3) ›": "NEXT: SUPPORT TOOLS (3/3) ›",
    "Ý Nghĩa Con Số (0 đến 3):": "What The Number Means (0 to 3):",
    "Con số thể hiện số cạnh trong bảng là tường vô hình của ô đó.": "The number counts how many sides of that cell hide an invisible wall.",
    "Ưu Tiên Đi Qua Ô Số 0:": "Prefer Walking Through 0 Cells:",
    "Ô số 0 không có bất kỳ tường nào, là lối đi thông suốt an toàn nhất.": "A 0 cell has no walls at all — the safest, fully open passage.",
    "Cẩn Thận Ô Số 2 & Số 3:": "Take Care With 2s & 3s:",
    "Có nhiều tường bao quanh, cần so sánh với các ô bên cạnh để tránh đâm tường!": "Many walls surround them — compare with neighboring cells to avoid wall hits!",
    "Ô SỐ 0 = AN TOÀN": "A 0 CELL = SAFE",
    "KHÔNG CÓ TƯỜNG": "NO WALLS",
    "Tự do đi qua theo mọi hướng": "Move through freely in any direction",
    "Ô SỐ 3 = 3 TƯỜNG": "A 3 CELL = 3 WALLS",
    "BỊ BỊT KÍN 3 MẶT": "3 SIDES SEALED",
    "Chỉ có 1 cạnh duy nhất để thoát": "Only 1 side left to escape",
    "Suy luận như Dò Mìn: Dùng con số để xác định khe nào có Tường Vô Hình": "Reason like Minesweeper: use the numbers to pinpoint which gaps hide Invisible Walls",
    "Công Cụ Trợ Giúp": "Helper Tools",
    "ĐÃ HIỂU • BẮT ĐẦU CHƠI": "UNDERSTOOD • START PLAYING",
    "Quan Sát & Đánh Dấu Tường Trước:": "Observe & Mark Walls First:",
    "Chưa vội vẽ đường ngay — hãy nối các Anchor để bịt các khe nguy hiểm trước.": "Don't draw right away — connect Anchors to seal the dangerous gaps first.",
    "Vẽ Chậm Rãi & Chắc Chắn:": "Draw Slowly & Surely:",
    "Kéo nét mực từng ô một từ Cầu thang Start sang Finish theo lối đã mở.": "Drag the ink line cell by cell from the Start stair to Finish along the opened path.",
    "Đạt 3 Sao Mỗi Màn:": "Earn 3 Stars Per Level:",
    "Hoàn thành cả 3 Thử Thách trên bảng HUD để gom trọn vẹn 3 Sao mở Chương mới!": "Clear all 3 Challenges on the HUD to collect all 3 Stars and unlock the next Chapter!",
    "CÔNG CỤ: GHI NHỚ": "TOOL: MEMORY",
    "Đánh dấu Tường Nghi Ngờ": "Mark Suspected Walls",
    "Kéo giữa 2 dấu cộng (+) ở góc ô để tự dựng": "Drag between the 2 plus signs (+) at cell corners to build",
    "tường cam nháp, giúp không bao giờ đâm nhầm!": "a draft orange wall so you never hit the wrong one!",
    "Lùi lại 1 bước": "Rewind 1 step",
    "Lỡ vẽ sai vào ngõ cụt? Bấm": "Drew into a dead end? Tap",
    "Undo để rút lại nét vẽ an toàn.": "Undo to safely pull the line back.",
    "GỢI Ý": "HINT",
    "Mở 1 bước an toàn": "Reveal 1 safe step",
    "Gặp thế cờ quá khó? Soi sáng": "Facing a brutal position? Light up",
    "ngay 1 đoạn đường đúng đắn.": "the next correct stretch right away.",
    "Kết hợp linh hoạt Vẽ Đường + Ghi Nhớ Tường để phá đảo mọi câu đố!": "Mix Draw Line + Wall Memory cleverly to crack every puzzle on the island!",
    # -------------------------------------------------------------------- sumpath
    "SUM PATH • TOÁN ĐỐ": "SUM PATH",
    "Bài Toán Cộng Tổng Điểm": "The Sum-Adding Puzzle",
    "QUY TẮC CỘNG TỔNG CƠ BẢN": "BASIC SUMMING RULES",
    "TIẾP THEO: TOÁN TỬ & Ô 1 LẦN (2/3) ›": "NEXT: OPERATORS & ONE-TIME CELLS (2/3) ›",
    "Bỏ qua hướng dẫn & Vào cộng điểm ngay": "Skip guide & start scoring now",
    "CỘNG TỔNG & MỤC TIÊU": "SUMS & TARGETS",
    "TOÁN TỬ & Ô 1 LẦN": "OPERATORS & ONE-TIME CELLS",
    "BÍ QUYẾT TÍNH & UNDO": "MATH TIPS & UNDO",
    "Con Số Là Điểm Số Của Ô (1 đến 9):": "The Number Is The Cell's Score (1 to 9):",
    "Không có tường chắn, không có bom ẩn. Mỗi ô trên bàn cờ đóng vai trò là một điểm số.": "No walls, no hidden bombs. Every cell on the board is simply a score value.",
    "Cộng Dồn Liên Tục Vào Tổng Điểm:": "Values Add Up Continuously:",
    "Mỗi khi nét vẽ kéo sang ô mới, điểm ô đó sẽ lập tức được cộng dồn vào thẻ Tổng Hiện Tại.": "Each time your line enters a new cell, its value is added straight to the Current Total card.",
    "Chạm Đích Khớp Đúng Mục Tiêu:": "Reach The Exit With The Exact Target:",
    "Chỉ chiến thắng khi bạn chạm Hố Thang Đích F với Tổng Điểm thỏa mãn đúng phép tính yêu cầu.": "You only win by touching the Finish hole F with a Total that satisfies the required math.",
    "TỔNG HIỆN TẠI": "CURRENT TOTAL",
    "(qua 3 ô)": "(over 3 cells)",
    "MỤC TIÊU PHẢI ĐẠT": "TARGET TO HIT",
    "CẦN THÊM +32": "NEED +32 MORE",
    "CỘNG DỒN ĐIỂM": "RUNNING SCORE",
    "= 18 ĐIỂM": "= 18 POINTS",
    "Cộng mỗi bước đi!": "Every step counts!",
    "ĐI TỰ DO": "FREE MOVEMENT",
    "Vẽ hướng nào cũng": "Draw in any direction",
    "không sợ đâm chết!": "with no fear of dying!",
    "Kéo qua ô nào, điểm ô đó cộng dồn vào Tổng. Đích đến yêu cầu bạn đạt chính xác = 50!": "Every cell you drag through adds to the Total. The exit demands exactly = 50!",
    "Toán Tử & Ô Điểm 1 Lần": "Operators & One-Time Cells",
    "QUY TẮC MỤC TIÊU & ĐIỂM Ô": "TARGET & CELL-SCORE RULES",
    "TIẾP THEO: CHIẾN THUẬT & UNDO (3/3) ›": "NEXT: TACTICS & UNDO (3/3) ›",
    "Để Ý Ký Hiệu Toán Tử (=, <, >):": "Watch The Operator (=, <, >):",
    "Với dấu =, tổng phải khớp tuyệt đối. Với dấu < hoặc >, chỉ cần tổng nằm trong khoảng hợp lệ.": "With =, the total must match exactly. With < or >, the total just needs to land in the valid range.",
    "Mỗi Ô Chỉ Tính Điểm Một Lần:": "Each Cell Scores Only Once:",
    "Bạn có thể vẽ đường giao cắt ô cũ để chuyển hướng, nhưng điểm ô đó sẽ không được cộng thêm.": "You may cross an old cell to change direction, but it adds no extra points.",
    "Về Đích Sai Mục Tiêu = Thất Bại:": "Wrong Total At The Exit = Failure:",
    "Dù bạn chạm được hố thang F nhưng tổng điểm không thỏa mãn phép tính thì màn chơi chưa kết thúc!": "Touching the F shaft is not enough — if the total fails the math, the level is not over!",
    "3 DẠNG TOÁN TỬ HUD": "3 HUD OPERATOR TYPES",
    "BẰNG CHÍNH XÁC": "EXACTLY EQUAL",
    "Ví dụ: Tổng = 50": "Example: Total = 50",
    "NHỎ HƠN MỨC TRẦN": "BELOW THE CEILING",
    "Ví dụ: Tổng < 35": "Example: Total < 35",
    "LỚN HƠN MỨC SÀN": "ABOVE THE FLOOR",
    "Ví dụ: Tổng > 40": "Example: Total > 40",
    "KIỂM TRA KỸ TOÁN TỬ": "CHECK THE OPERATOR CAREFULLY",
    "trên bảng HUD trước khi vẽ!": "on the HUD before you draw!",
    "MỖI Ô CHỈ CỘNG 1 LẦN": "EACH CELL ADDS ONLY ONCE",
    "+0 ĐIỂM": "+0 POINTS",
    "KHÔNG THỂ ĐI VÒNG CÀY ĐIỂM": "NO FARMING BY LOOPING",
    "Quay lại ô cũ sẽ không cộng thêm.": "Re-entering an old cell adds nothing.",
    "Điểm chỉ tính ở lần bước đầu tiên!": "Points count only on the first visit!",
    "Luôn nhìn toán tử trên HUD: Có màn yêu cầu = 50, nhưng có màn chỉ yêu cầu < 30!": "Always read the HUD operator: some levels demand = 50, others only < 30!",
    "Chiến Thuật & Undo Sửa Sai": "Tactics & Undo Fixes",
    "BÍ QUYẾT TÍNH TOÁN": "MATH SECRETS",
    "ĐÃ HIỂU • BẮT ĐẦU CỘNG ĐIỂM": "UNDERSTOOD • START SCORING",
    "Bản Cờ Luôn Có Ít Nhất 1 Nghiệm Đúng:": "Every Board Has At Least 1 Correct Solution:",
    "Mỗi màn đều đảm bảo có ít nhất một đường đi hoàn hảo thỏa mãn đúng toán tử mục tiêu.": "Each level guarantees at least one perfect route that satisfies the target operator.",
    "Dùng Undo Để Thu Hồi Điểm Lố:": "Use Undo To Recover Overshoot:",
    "Nếu lỡ bước vào ô số to khiến tổng vượt quá mục tiêu, chỉ cần Undo lùi lại để trừ điểm ra.": "If a big cell pushes the total past the target, just Undo back and the points come off.",
    "Đua Tốc Độ Phá Giải:": "Race To Solve Fastest:",
    "Game không giới hạn số bước — người nhẩm tính nhanh và về đích sớm nhất sẽ đạt hạng cao!": "No step limit — the quickest mental math and earliest finish earns the top rank!",
    "CHIẾN THUẬT: SỐ LỚN & SỐ NHỎ": "TACTIC: BIG & SMALL NUMBERS",
    "Ô 7, 8, 9": "Cells 7, 8, 9",
    "Dồn điểm cực nhanh": "Bank points fast",
    "Ô 1, 2, 3": "Cells 1, 2, 3",
    "Tinh chỉnh vừa khít": "Fine-tune the exact fit",
    "50 ĐIỂM": "50 POINTS",
    "HOÀN HẢO": "PERFECT",
    "Khi mục tiêu còn xa: Ưu tiên gom các ô số to. Khi gần chạm mốc: Rẽ qua ô số nhỏ để chốt hạ!": "Far from the target: grab big cells. Close to it: swing through small cells to nail the finish!",
    "TRỪ NGƯỢC ĐIỂM SỐ": "POINTS REFUNDED",
    "LỠ CỘNG LỐ ĐIỂM? SỬA NGAY!": "OVERSHOT THE TOTAL? FIX IT NOW!",
    "Bấm Undo lùi lại 1 bước, điểm số của ô đó": "Tap Undo one step and the last cell's points",
    "sẽ được trừ ngược ra khỏi Tổng Hiện Tại để bạn chọn nhánh khác.": "are subtracted from the Current Total so you can pick another branch.",
    "Luôn có ít nhất 1 nghiệm đúng! Hãy tận dụng Undo để thử nghiệm các hướng tính toán.": "There is always at least 1 correct solution! Use Undo to test different math routes.",
    # --------------------------------------------------------------- time_attack
    "TIME ATTACK MAZE": "TIME ATTACK MAZE",
    "Đồng Hồ Đếm Ngược": "The Countdown Clock",
    "QUY TẮC ĐUA THỜI GIAN": "TIME RACE RULES",
    "TIẾP THEO: ĐÂM TƯỜNG MẤT GIỜ (2/3) ›": "NEXT: WALL HITS COST TIME (2/3) ›",
    "Bỏ qua hướng dẫn & Vào đua giờ ngay": "Skip guide & start the race now",
    "ĐỒNG HỒ ĐẾM NGƯỢC": "COUNTDOWN CLOCK",
    "ĐÂM TƯỜNG MẤT GIỜ": "WALL HITS COST TIME",
    "TỐC ĐỘ & GỢI Ý": "SPEED & HINTS",
    "Thời Gian Tổng Đếm Ngược:": "The Total Time Counts Down:",
    "Màn chơi cấp một quỹ thời gian cố định (60s - 120s). Bạn phải chạm hố thang F trước khi hết giờ.": "Each level grants a fixed time budget (60s - 120s). You must touch the F shaft before time runs out.",
    "Không Giới Hạn Số Bước Chân:": "No Step Limit:",
    "Bạn có thể đi vòng, thử nhiều ngã rẽ mà không sợ hết bước — kẻ thù duy nhất là thời gian trôi.": "Loop around and try branches freely — the only enemy is the ticking clock.",
    "Quy Luật Tường Vô Hình Như Thường:": "Invisible Walls Work As Usual:",
    "Con số trên ô vẫn là số tường (0 - 4). Vừa đi nhanh vừa phải suy luận né tường chính xác.": "Cell numbers still count walls (0 - 4). Sprint while reasoning precisely to dodge them.",
    "THỜI GIAN CÒN LẠI": "TIME REMAINING",
    "ĐANG GIẢM": "TICKING DOWN",
    "ÁP LỰC THỜI GIAN": "TIME PRESSURE",
    "ĐẾM NGƯỢC": "COUNTDOWN",
    "VỀ 00:00": "TO 00:00",
    "Hết giờ = THUA!": "Time up = LOSS!",
    "SỐ BƯỚC CHÂN": "STEP COUNT",
    "KHÔNG GIỚI HẠN": "UNLIMITED",
    "Đi bao nhiêu ô tùy ý": "Walk as many cells as you like",
    "chỉ cần về đích kịp!": "just get there in time!",
    "Bạn chỉ có 60s đến 120s: Hãy vẽ thật dứt khoát trước khi đồng hồ điểm 00:00!": "You only have 60s to 120s: draw decisively before the clock hits 00:00!",
    "Đâm Tường & Mất Giờ": "Wall Hits & Lost Time",
    "HẬU QUẢ VA CHẠM TƯỜNG": "WALL IMPACT RESULTS",
    "TIẾP THEO: TỐC ĐỘ & GỢI Ý (3/3) ›": "NEXT: SPEED & HINTS (3/3) ›",
    "Văng Ngược Về Cầu Thang Start (S):": "Bounced Back To The Start Stair (S):",
    "Đâm phải tường vô hình, nhân vật lập tức bị đẩy lùi về điểm S để bắt đầu đường vẽ mới.": "Hit an invisible wall and your piece is shoved back to S to begin a new line.",
    "Đồng Hồ Vẫn Tiếp Tục Đếm Ngược:": "The Clock Keeps Counting:",
    "Thời gian không dừng lại. Việc vẽ lại từ đầu khiến bạn mất đứt nhiều giây sinh tử!": "Time never stops. Redrawing from scratch burns precious seconds!",
    "Rút Kinh Nghiệm Từ Đoạn Tường Vừa Lộ:": "Learn From The Wall You Just Revealed:",
    "Bức tường bị đâm sẽ lộ ra vĩnh viễn. Hãy nhìn thật nhanh và vẽ đường né tránh dứt khoát.": "The wall you hit stays revealed forever. Glance fast and draw a decisive detour.",
    "BỊ ĐẨY VỀ XUẤT PHÁT": "SHOVED BACK TO START",
    "VẼ LẠI TỪ S!": "REDRAW FROM S!",
    "Tường lộ diện nhưng": "The wall is revealed but",
    "phải đi lại từ đầu.": "you must walk it all again.",
    "THỜI GIAN VẪN TRÔI": "TIME KEEPS FLOWING",
    "MẤT 5 - 10 GIÂY!": "5 - 10 SECONDS LOST!",
    "Đồng hồ vẫn đếm lùi,": "The clock keeps counting down,",
    "quỹ giờ cạn rất nhanh!": "and the budget drains fast!",
    "Đâm tường ở Time Attack không chết ngay, nhưng sẽ cướp đi thời gian quý báu của bạn!": "Wall hits in Time Attack don't kill you — but they rob you of precious seconds!",
    "Tốc Độ & Gợi Ý Cứu Nguy": "Speed & Rescue Hints",
    "BÍ QUYẾT BỨT TỐC": "BURST-SPEED SECRETS",
    "ĐÃ HIỂU • ĐUA THỜI GIAN": "UNDERSTOOD • RACE THE CLOCK",
    "Tìm Ô Số 0 Để Phóng Nhanh:": "Find 0 Cells To Sprint:",
    "Quét mắt tìm các ô số 0 trước tiên để vạch nhanh tuyến đường an toàn mà không tốn công nhẩm tính.": "Scan for 0 cells first to sketch a safe route fast without mental math.",
    "Bấm Gợi Ý Khi Bị Bí Quá 3 Giây:": "Hit Hint After 3 Seconds Of Being Stuck:",
    "Trong Time Attack, do dự là thất bại. Hãy bấm Gợi Ý để mở khóa nút thắt thay vì để đồng hồ cạn kiệt.": "In Time Attack, hesitation is defeat. Tap Hint to break the knot instead of burning the clock.",
    "Dùng Undo Kịp Thời Để Tránh Về S:": "Use Undo In Time To Avoid Going Back To S:",
    "Nếu cảm giác vừa rẽ nhầm nhánh bế tắc, bấm Undo lùi lại 1 ô sẽ nhanh hơn rất nhiều so với bị phạt về S!": "If a branch feels like a dead end, Undo one cell — far faster than the penalty back to S!",
    "CHIẾN THUẬT: PHÓNG QUA Ô 0": "TACTIC: BLITZ THROUGH 0 CELLS",
    "LƯỚT QUA • SIÊU TỐC": "SWIPE THROUGH • TURBO",
    "Ưu Tiên Ô Số 0 Để Tăng Tốc": "Prioritize 0 Cells To Gain Speed",
    "Ô số 0 hoàn toàn không có tường bao.": "A 0 cell has no walls around it.",
    "Hãy phóng thẳng bút qua ô này mà không": "Sprint your pen straight through it without",
    "cần dừng lại suy nghĩ, tiết kiệm tối đa giây!": "pausing to think — saving every second!",
    "Mở lối khi bí": "Open the way when stuck",
    "Bí quá 3 giây? Đừng chôn chân!": "Stuck over 3 seconds? Don't freeze!",
    "Bấm ngay Gợi Ý để soi đường": "Tap Hint at once to light the route",
    "thay vì đứng nhìn đồng hồ cạn!": "instead of watching the clock drain!",
    "Rút bước kịp thời": "Retreat in time",
    "Lỡ tay quẹt nhầm hướng?": "Swiped the wrong way?",
    "Bấm Undo lùi lại ngay": "Tap Undo immediately",
    "để không bị đâm tường văng về S!": "so you don't hit a wall and fly back to S!",
    "Đứng yên là tự sát! Khi phân vân, bấm ngay Gợi Ý để cứu lấy thời gian sống còn.": "Standing still is suicide! When in doubt, tap Hint and save your remaining time.",
    # ------------------------------------------------------------- token tran
    "S": "S",
    "F": "F",
    "UNDO": "UNDO",
}
